spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dboauth2
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8888
application:
  security:
    jwt:
      secret-key: 7f312164792f0ab848c987b7e0980807faddf42cc19d284e0822ce40888a30b59f4701bee6574a7eacdc8d6498f970462b25db28c512e8a6bbf218deb6294db5
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days